name: ':bug: Bug'
description: Report an error or bug.
title: ':bug: <TITLE>'
type: Bug
labels: ['bug', 'triage']

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: Describe the expected behaviour.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the bug.
      placeholder: |
        1. Navigate to ...
        2. Click on ...
        3. Error occurs
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Provide any other relevant details.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide screenshots if applicable.
