name: "🐛 Bug"
description: Report a bug.
title: "🐛 <TITLE>"
type: Bug

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug here.
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the bug here.
      placeholder: |
        1. Navigate to ...
        2. Click on ...
        3. Error occurs
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: Describe the expected behaviour here.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Provide any other relevant information here.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide screenshots here.
