name: ':memo: Documentation'
description: Request improvements or additions to documentation.
title: ':memo: <TITLE>'
type: Documentation
labels: ['documentation']

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the proposed changes.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Provide any other relevant details.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide screenshots if applicable.
