name: "🧱 Infrastructure"
description: Request improvements or additions to infrastructure resources.
title: "🧱 <TITLE>"
type: Infrastructure

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the proposed changes.
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Describe why the proposed changes are required.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Describe any other relevant details.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide screenshots if applicable.
