name: "👷 Infrastructure"
description: Request the creation or modification of infrastructure resources.
title: "👷 <TITLE>"
type: Infrastructure

body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Request Type
      options:
        - Create
        - Modify
        - Delete

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the required changes here.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Describe any other relevant information here.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide screenshots here.
